### ISSUE TITLE
Plugin fails on Rider 2019.3

### ISSUE THREAD

**Issue by desaroger** [git-time-metric/gtm-jetbrains-plugin#12]
## Summary
I was working with Rider 2018 and everything worked nicely, but when I updated Rider to 2019.3 the plugin crashes on init and Rider disables it.

## Here is the output log of the exception
```
Plugin 'io.edgeg.gtm.intellij' failed to initialize and will be disabled.  Please restart JetBrains Rider.

java.lang.NullPointerException
    at io.edgeg.gtm.intellij.GTMStatusWidget.<init>(GTMStatusWidget.java:30)
    at io.edgeg.gtm.intellij.GTMStatusWidget.create(GTMStatusWidget.java:43)
    at io.edgeg.gtm.intellij.GTMProject.initComponent(GTMProject.java:24)
    at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:42)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:110)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:72)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:65)
    at com.intellij.serviceContainer.PlatformComponentManagerImpl.createComponents(PlatformComponentManagerImpl.kt:177)
    at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:295)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.initProject(ProjectManagerImpl.java:315)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.loadProject(ProjectManagerImpl.java:337)
    at com.jetbrains.rider.projectView.SolutionManager.a(SolutionManager.kt:295)
    at com.jetbrains.rider.projectView.SolutionManager.access$openIdeaProject(SolutionManager.kt:38)
    at com.jetbrains.rider.projectView.SolutionManager$openSolution$1.invoke(SolutionManager.kt:224)
    at com.jetbrains.rider.projectView.SolutionManager$openSolution$1.invoke(SolutionManager.kt:38)
    at com.jetbrains.rider.projectView.SolutionManager.a(SolutionManager.kt:250)
    at com.jetbrains.rider.projectView.SolutionManager.openSolution(SolutionManager.kt:222)
    at com.jetbrains.rider.projectView.ideaInterop.RiderRecentProjectsManager.openProject(RiderRecentProjectsManager.kt:131)
    at com.intellij.ide.ReopenProjectAction.actionPerformed(ReopenProjectAction.java:70)
    at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:266)
    at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:83)
    at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:149)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:281)
    at com.intellij.openapi.wm.impl.welcomeScreen.RecentProjectPanel$3.onClick(RecentProjectPanel.java:144)
    at com.intellij.ui.ClickListener$1.mouseReleased(ClickListener.java:59)
    at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
    at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
    at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
    at java.desktop/java.awt.Component.processMouseEvent(Component.java:6651)
    at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
    at java.desktop/java.awt.Component.processEvent(Component.java:6416)
    at java.desktop/java.awt.Container.processEvent(Container.java:2263)
    at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
    at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
    at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
    at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
    at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
    at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
    at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
    at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
    at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
    at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
    at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
    at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
    at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:906)
    at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:844)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:776)
    at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:422)
    at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:421)
    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

  ```

## Environment
- Windows 10
- GTM v1.3.5
- GTM Jetbrains Plugin v1.0.13
- Jetbrains Rider 2019.3 (Build #RD-193.5233.171, built on December 10, 2019)

**Comment by GreyTeardrop** [comment]
Looks like GTM Plugin is not compatible with Jetbrains platform 2019.3. I have a similar issue with IntelliJ IDEA 2019.3.1. Issue #11 seems to be related as well.

**Comment by Querschlag** [comment]
The fix for this has already been merged. Only thing missing is a new release on [plugins.jetbrains.com](https://plugins.jetbrains.com/plugin/8494-git-time-metric)

Relevant issue: https://github.com/git-time-metric/gtm-jetbrains-plugin/issues/9#issuecomment-564018316

**Comment by desaroger** [comment]
When will be available in plugins.jetbrains.com? There is a way to use the plugin without waiting to be published?

Thanks!

Edit: I also realized there is not a github release since 2017, this is normal?

**Comment by Querschlag** [comment]
You can either build the plugin from source, or use my build: [gtm-intellij.zip](https://github.com/git-time-metric/gtm-jetbrains-plugin/files/4032078/gtm-intellij.zip)

@mschenk42 Are you able to publish this as a new release on plugins.jetbrains.com?

**Comment by desaroger** [comment]
Thanks @Querschlag! Now it works perfectly with your build.

Do you want me to close the issue or do you prefer to wait the response from @mschenk42?

**Comment by mschenk42** [comment]
I recently lost the setup I used to publish this plugin and no longer use the JetBrain's IDE.  @Querschlag would you be able to publish this updated plugin with JetBrain's plugin repo under your own account?  I can refer to your version of the plugin from the GTM JB plugin account.

**Comment by Querschlag** [comment]
@mschenk42
I think linking from the plugin page would result in a poor experience as none of the current users would be able to update their plugin automatically, but instead would need to install the new one. It would also cause confusion for new users when searching for "GTM" yielded 2 plugins.
As far as I know there is no way of transferring ownership of a plugin to another account.
So maybe, if you are no longer using your JetBrains Account, you could give me access and I can handle deployment.

**Comment by millsoft** [comment]
Same problem with phpstorm.
I installed the zip from @Querschlag and it seems to work now (thanks!). Why cant this be updated to the jetbrains plugins repository?
